scss_files: "src/styles/**/*.scss"

linters:
  ColorVariable:
    enabled: false

  DuplicateProperty:
    enabled: false

  Indentation:
    allow_non_nested_indentation: true

  PseudoElement:
    enabled: false

  SelectorFormat:
    enabled: false

  StringQuotes:
    style: double_quotes

  VendorPrefix:
    enabled: false

